name: Code style

on: [ push ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NPM Dependencies
        run: npm install --legacy-peer-deps
      - name: Run ESLint
        run: ./node_modules/.bin/eslint --ext .js,.vue src
